name: fn4.pytorch
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults

dependencies:
  - python=3.9

  - conda-forge::matplotlib
  - conda-forge::numpy
  - conda-forge::scipy

  - pip:
      - -e .[dev]
  - pip:
      - accelerate
      - aiohappyeyeballs
      - aiohttp
      - aiosignal
      - annotated-types
      - anyio
      - async-timeout
      - attrs
      - blinker
      - charset-normalizer
      - click
      - ctransformers
      - dataclasses-json
      - distro
      - executing
      - flask
      - frozenlist
      - greenlet
      - h11
      - httpcore
      - httpx
      - httpx-sse
      - huggingface-hub
      - idna
      - itsdangerous
      - jiter
      - jsonpatch
      - jsonpointer
      - langchain
      - langchain-community
      - langchain-core
      - langchain-openai
      - langchain-text-splitters
      - langsmith
      - marshmallow
      - multidict
      - mypy-extensions
      - openai
      - orjson
      - propcache
      - py-cpuinfo
      - pydantic
      - pydantic-core
      - pydantic-settings
      - python-dotenv
      - pyyaml
      - regex
      - requests
      - requests-toolbelt
      - safetensors
      - sentencepiece
      - sniffio
      - sqlalchemy
      - tenacity
      - tiktoken
      - tokenizers
      - torch-geometric
      - torchtext
      - tqdm
      - transformers
      - typing-inspect
      - urllib3
      - werkzeug
      - yarl
      - zstandard
      - nupic.torch

